streamlined testelf, loading one workspace at a time.
vivisect/vivisect pull request #340
Opened 2021-01-15 05:57 UTC by atlas0fd00m

2021-01-16 08:22 UTC, rakuy0 requested changes
Just a couple minor things.

Can confirm reduces memory usage for this test.

2021-01-17 06:02 UTC, atlas0fd00m commented on vivisect/tests/testelf.py
> +            log.warn("ERROR in analysis module: (%r): %r", mod, e)
good catch.  done.

2021-01-17 06:14 UTC, atlas0fd00m commented on vivisect/tests/testelf.py
> +            fname = path[-1]
??
i'm not sure what you mean.

2021-01-17 06:14 UTC, atlas0fd00m commented on vivisect/tests/testelf.py
> +            fname = path[-1]
plus, i'm doing away with fname.  i've found a better way to identify the prefix for names starting with file.

2021-01-17 06:25 UTC, atlas0fd00m commented on vivisect/tests/testelf.py
> +    def names(self, vw, test_data, fname):
yes!  thank you.  fixed.

2021-01-17 06:27 UTC, atlas0fd00m commented on vivisect/tests/testelf.py
> +name_prefix_skips = [   # (prefix, MustHavePtrPrefix),
i might agree with you, but it is only ever used here in genNames(), and doesn't serve much other purpose.  i don't see benefit of it being in helpers, but if you like i can move it there.

2021-01-18 06:36 UTC, rakuy0 approved these changes

2021-01-18 06:36 UTC, rakuy0 commented on vivisect/tests/testelf.py
> +name_prefix_skips = [   # (prefix, MustHavePtrPrefix),
For now it's fine here.

2021-01-18 12:26 UTC, rakuy0 commented on vivisect/tests/testelf.py
> +            fname = path[-1]
Oh, I was just referring to getting rid of the fname variable and outputting the whole path, but if you've got a better way for identifying the prefix for file names, I'm cool with that too.

2021-01-18 14:40 UTC, merged