Extensions enhancement
vivisect/vivisect pull request #341
Opened 2021-01-15 22:44 UTC by atlas0fd00m

example_gui_extensions.py gets some examples as well.

2021-01-21 05:24 UTC, rakuy0 requested changes
Mostly some compat stuff. At some point would you mind driving me through thisso I can see it work, since this kind of thing is a mess to test?

2021-01-21 23:59 UTC, atlas0fd00m commented on vivisect/extensions/example_gui_extension.py
> +    print s % args
done

2021-01-21 23:59 UTC, atlas0fd00m commented on vivisect/extensions/example_gui_extension.py
> +        print "foobar"
deleted

2021-01-22 00:00 UTC, atlas0fd00m commented on vivisect/extensions/example_gui_extension.py
> +        print e
deleted

2021-01-22 00:00 UTC, atlas0fd00m commented on vivisect/extensions/example_gui_extension.py
> +        vprint(self.vw, '%r:  %r', ok, utext)
actually no.  this is as intended.

2021-01-22 00:01 UTC, atlas0fd00m commented on vivisect/qt/ctxmenu.py
> +        print exthook, vw, va, expr, menu, parent, nav
deleted and logging changed to info

2021-01-22 05:13 UTC, atlas0fd00m commented on vivisect/__init__.py
> +        self._ext_ctxmenu_hooks = []
a plague on you and your house.

2021-01-22 05:13 UTC, atlas0fd00m commented on vivisect/__init__.py
> +        self._ext_ctxmenu_hooks = []
;)  that took longer than all the other changes put together, and introduced fails.  it was more indepth than i had time for.  should be better now.

2021-01-25 05:34 UTC, rakuy0 approved these changes
One question and a couple aesthetic things, but nothing that generally mucks with the functioning.

2021-01-25 20:52 UTC, atlas0fd00m commented on vivisect/__init__.py
> +            self._extensions[name] = extmod
we can later if we want. currently i think no.

2021-01-26 15:45 UTC, rakuy0 approved these changes

2021-01-26 21:38 UTC, merged