Recon x64
vivisect/vivisect pull request #56
Opened 2015-03-17 22:12 UTC by cmaruti

Improved support for x64 systems

2015-03-26 13:43 UTC, invisig0th commented on vdb/recon/__init__.py
> +    if "64" in trace.getMeta("Architecture"):
Love the overall idea, however for future proofing, we cannot assume that any arch with the chars "64" in the name ( such as commodore64 ) are amd64.  This probably needs to be come something more like a dict lookup of
(arch,plat):cc

2015-03-26 13:47 UTC, invisig0th commented on vdb/recon/__init__.py
> +        else: trace.getEmulator().getCallingConvention("sysvamd64call")
inline "else: foo" is not style compatible with the rest of the code, i know it's a nit but if we dont try to "dig up" the code base will only become more inconsistent :)

2015-03-26 13:47 UTC, invisig0th commented on vdb/recon/__init__.py
perfect.  heading down this road, we'll hopefully manage to support windows arm without too much trouble :)

2015-03-26 13:48 UTC, invisig0th commented on vdb/recon/sniper.py
> +    if "64" in trace.getMeta("Architecture"):
another instance of "fuzzy" substring comparison.  on amd64, the "Architecture" meta will always be exactly "amd64" so lets test for that.

2015-06-15 14:00 UTC, cmaruti commented
Do you need something else here man before merge?

2019-01-08 17:35 UTC, atlas0fd00m commented
@cmaruti does this PR still function as expected on current Viv/Vdb?

2019-01-08 22:47 UTC, cmaruti commented
I don’t know atm; gonna check it

2019-04-01 09:42 UTC, cmaruti commented
@atlas0fd00m seems the whole breakpoint stuffs on win32 (32/64) does not work anymore :(

BEFORE merging master branch into
>  python sample06_sniper.py
RECON: 1260 0x76c3ec44 user32.CreateWindowExW(256, u'CalcFrame', u'Calcolatrice', 13238272)
RECON: 1260 0x76c3ec44 user32.CreateWindowExW(0, u'CalcFrame', NULL, 1073741824)
RECON: 1260 0x76c3ec44 user32.CreateWindowExW(0, u'EDIT', u'', 268435456)
RECON: 1260 0x76c3ec44 user32.CreateWindowExW(0, u'STATIC', u'', 1342177358)
RECON: 1260 0x76c3ec44 user32.CreateWindowExW(0, 0x0000c03b, u'OleMainThreadWndName', 2281701376L)
RECON: 1260 0x76c3ec44 user32.CreateWindowExW(0, u'CicMarshalWndClass', u'CicMarshalWnd', 2281701376L)
RECON: 1260 0x76c3ec44 user32.CreateWindowExW(0, u'MSCTFIME UI', u'MSCTFIME UI', 2281701376L)

AFTER merging master branch
> NO breakpoints hit

```python
import sys
VDB_ROOT = "C:\\vivisect"
sys.path.append(VDB_ROOT)

import vtrace
import vtrace.breakpoints as v_bp
import vdb.recon as v_rec
import vdb.recon.sniper as v_snip

def hookfunc(event, trace, retaddr, args, cc):
    print('ret: 0x%.8x: %r' % (retaddr, args))
    
trace = vtrace.getTrace()

#v_snip.snipeDynArg(trace, 'user32.CreateWindowExW', 3)
#v_snip.snipeArgValue(trace, 'user32.CreateWindowExW', 1, 0x100)
#v_bp.addHook( trace, 'user32.CreateWindowExW', hookfunc )
v_rec.addReconBreak(trace, 'user32.CreateWindowExW', 'IUUI')

trace.execute(r'c:\windows\system32\calc.exe')
trace.setMode('RunForever', True)
trace.run()

2022-07-22 16:36 UTC, atlas0fd00m commented
Windows has added significant changes to the debugging security model, requiring more permissions to *write* to a debugged process.  since Breakpoints actually overwrite bytes in the target process (for Intel, Viv writes the Int3 instruction, or 0xCC at the breakpoint location).

but wait, you're suggesting that this change has to do with an update to Viv?

i apologize for the delay in responding, @cmaruti .  i didn't realize you had (bad notification mechanisms for me apparently).

can you give me more information about what version you were using before breakpoints stopped working?  a date?

2022-07-23 10:14 UTC, cmaruti commented
Since a long time has passed can't be helpful. Probably the best approx was the date around the post before my last one

2022-07-28 12:38 UTC, atlas0fd00m commented
my apologies, @cmaruti , apparently github stopped sending me email notifications and i only now realized it.
thank you for your contributions.

i'm working out why this stopped working for you and will have a PR done soon.

2022-07-29 10:33 UTC, cmaruti commented
Np sir! I'll be more than happy to check it out later when done

2022-08-27 02:49 UTC, atlas0fd00m commented
hey @cmaruti 
thank you for your patience...
could you see if this branch of Viv changes anything for you?

i'm not sure if this is a necessary change, since i think i've been running into issues where the user account simply lacks the permissions overall.  but that doesn't answer *your* problem.

https://github.com/atlas0fd00m/vivisect/tree/win_vdb_privs

https://github.com/vivisect/vivisect/pull/536


thanks!
@

2022-08-29 12:19 UTC, cmaruti commented
Hi @atlas0fd00m nothing changed from my side. Now I got the following trace and seems problem is elsehwere...

```
C:\vivisect-win_vdb_privs>python sample.py
Failed to resolve breakpoint address for expression: user32.CreateWindowExW
Error:
Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 22, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 37, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\breakpoints.py", line 98, in resolveAddress
    self.address = trace.parseExpression(self.vte)
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\__init__.py", line 939, in parseExpression
    return int(e_expr.evaluate(expression, vlocs))
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 40, in evaluate
    raise ExpressionFail(pycode, e)
envi.expression.ExpressionFail: ExpressionFail: 'user32.CreateWindowExW' is not a valid expression in this context (NameError("name 'user32' is not defined"))
Failed to resolve breakpoint address for expression: user32.CreateWindowExW
Error:
Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 22, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 37, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\breakpoints.py", line 98, in resolveAddress
    self.address = trace.parseExpression(self.vte)
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\__init__.py", line 939, in parseExpression
    return int(e_expr.evaluate(expression, vlocs))
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 40, in evaluate
    raise ExpressionFail(pycode, e)
envi.expression.ExpressionFail: ExpressionFail: 'user32.CreateWindowExW' is not a valid expression in this context (NameError("name 'user32' is not defined"))
Failed to resolve breakpoint address for expression: user32.CreateWindowExW
Error:
Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 22, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 37, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\breakpoints.py", line 98, in resolveAddress
    self.address = trace.parseExpression(self.vte)
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\__init__.py", line 939, in parseExpression
    return int(e_expr.evaluate(expression, vlocs))
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 40, in evaluate
    raise ExpressionFail(pycode, e)
envi.expression.ExpressionFail: ExpressionFail: 'user32.CreateWindowExW' is not a valid expression in this context (NameError("name 'user32' is not defined"))
Failed to resolve breakpoint address for expression: user32.CreateWindowExW
Error:
Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 22, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 37, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\breakpoints.py", line 98, in resolveAddress
    self.address = trace.parseExpression(self.vte)
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\__init__.py", line 939, in parseExpression
    return int(e_expr.evaluate(expression, vlocs))
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 40, in evaluate
    raise ExpressionFail(pycode, e)
envi.expression.ExpressionFail: ExpressionFail: 'user32.CreateWindowExW' is not a valid expression in this context (NameError("name 'user32' is not defined"))
Failed to resolve breakpoint address for expression: user32.CreateWindowExW
Error:
Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 22, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 37, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\breakpoints.py", line 98, in resolveAddress
    self.address = trace.parseExpression(self.vte)
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\__init__.py", line 939, in parseExpression
    return int(e_expr.evaluate(expression, vlocs))
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 40, in evaluate
    raise ExpressionFail(pycode, e)
envi.expression.ExpressionFail: ExpressionFail: 'user32.CreateWindowExW' is not a valid expression in this context (NameError("name 'user32' is not defined"))
Failed to resolve breakpoint address for expression: user32.CreateWindowExW
Error:
Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 22, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\envi\expression.py", line 37, in evaluate
    val = eval(pycode, {}, locvars)
  File "<string>", line 1, in <module>
NameError: name 'user32' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\breakpoints.py", line 98, in resolveAddress
    self.address = trace.parseExpression(self.vte)
  File "C:\vivisect-win_vdb_privs\vivisect-win_vdb_privs\vtrace\__init__.py", line 939, in p [...]

2022-08-29 19:53 UTC, atlas0fd00m commented
thanks for checking.
that is certainly odd.  a very unexpected error.
that looks like it's failing to lookup expressions, looking for user32 functions.

can you give me any more specifics about what you think is causing this?  i don't recognize that issue so it's hard to track it down on my side.  

also, did you install pywin32?

2022-08-29 19:53 UTC, atlas0fd00m commented
can you share what's in `sample.py`?

2022-08-29 21:55 UTC, cmaruti commented
Yep was totally unexpected also for me... 
pywin32 was installed and here you go with the contents of  `sample.py`

```
import sys
VDB_ROOT = "C:\\Users\\cmaruti\\Downloads\\vivisect-win_vdb_privs\\vivisect-win_vdb_privs\\"
sys.path.append(VDB_ROOT)

import vtrace
import vtrace.breakpoints as v_bp
import vdb.recon as v_rec
import vdb.recon.sniper as v_snip

def hookfunc(event, trace, retaddr, args, cc):
    print('ret: 0x%.8x: %r' % (retaddr, args))
    
trace = vtrace.getTrace()

#v_snip.snipeDynArg(trace, 'user32.CreateWindowExW', 3)
#v_snip.snipeArgValue(trace, 'user32.CreateWindowExW', 1, 0x100)
#v_bp.addHook( trace, 'user32.CreateWindowExW', hookfunc )
v_rec.addReconBreak(trace, 'user32.CreateWindowExW', 'IUUI')

trace.execute(r'c:\windows\system32\calc.exe')
trace.setMode('RunForever', True)
trace.run()
```

2022-08-30 02:43 UTC, atlas0fd00m commented
thanks, @cmaruti . i'll look into it.  

just to level-set on your environment, could you try using VDB on your machine, both mainline and this branch and let me know if you are able to set breakpoints on both (just standard VDB).

thanks@

2022-09-05 15:30 UTC, cmaruti commented
Hi @atlas0fd00m and sorry for the late reply; I have been away from the pc for a while

I did a silly mistake in my script tracked down thanks to your input :D! I can confirm both of the branches (main and priv) work well with the recon commit on my Win10 box; I have also update the posted script for your convenience

2022-09-06 17:12 UTC, atlas0fd00m commented on vdb/recon/__init__.py
> +def detect_cc(trace):
i like this approach (calling `detect_cc`) much better than inline hand-jamming...

please define the dictionary outside the function, so it doesn't get recreated every call.

also, these are the defaults (although i386/linux should be cdecl), but not necessarily the reality.  what happens when the code gets it wrong?  what's worst-case scenario?

thanks!

2022-09-06 17:13 UTC, atlas0fd00m commented on vdb/recon/sniper.py
> +
please only one copy of `detect_cc`

2022-09-08 09:23 UTC, cmaruti commented
I did my homework; hope it is fine @atlas0fd00m :D

2022-09-14 02:57 UTC, rakuy0 commented
@cmaruti Neat. Looks good so far.

You mind throwing in a unit test kinda demonstrating it in action (and so @atlas0fd00m/myself know if we accidentally break it when we're down in vdb town).

2022-09-30 14:18 UTC, atlas0fd00m commented
hey @cmaruti ,  looking good, thanks for the improvements.  

let me know if you want to chat about some good unittests (and how to wrap them into our testing framework).  that's all that's keeping us from merging this in.  well, that and merging in the base branch.

@rakuy0 and i just want to be sure we know if we break something moving forward.  keeps us honest and improves the overall quality of vivisect.  if you look back through our merged PR's, he and i are pretty frequently saying "hey, looks good!  where's the tests?"  lol.

thanks, man,
@

2022-09-30 14:36 UTC, cmaruti commented
Sorry guys but unfortunately I had no time to put togheter an unit test but I will do in the upcoming weeks. I'm not good at that but I'll try to get by

2022-10-30 22:32 UTC, atlas0fd00m requested changes
sorry for the delay in response.  i've been sitting on this review, trying to get the libc.exit hook fixed.  i now have a fix in, and ready for moving forword.

currently your unittest fails.  let's figure out why and then we can get this merged in.
unfortunately i believe part of this failure could be waiting on #550

2022-10-30 22:32 UTC, atlas0fd00m commented on vdb/tests/testrecon.py
> +                                                      'helloworld.exe')
alternately, making it support all the Intel platforms would be even better.

2022-11-02 13:05 UTC, cmaruti commented on vdb/tests/testrecon.py
> +                                                     'helloworld.exe'))
I am going to approve all of your suggested changes; in the meantime I'll try to find a sample in the vivtestfile repo that fit the use case and later extend the unit test

2022-12-30 15:50 UTC, atlas0fd00m commented
@cmaruti , could you pull in the latest master branch?  @invisig0th just merged in a fix allowing Linux systems to pick-up library loads as they occur (which would affect your unittests).

thanks!
@

2023-01-06 00:10 UTC, cmaruti commented
@atlas0fd00m CI tests failed once again :(

2023-01-10 22:50 UTC, atlas0fd00m commented
so the other error went away tho.  recon *is* working on AMD64.  i'm guessing it is failing on i386 because of a test issue rather than a recon/vdb issue.  we're getting close!

2023-01-18 18:15 UTC, atlas0fd00m commented
@cmaruti , would you like any help on this?
DM me in Synapse Slack if you'd like more back-and-forth conversation.

thanks again!
@

2023-01-20 15:32 UTC, cmaruti commented
Hi @atlas0fd00m and sorry for the late response...
I tracked down the problem and I'm pretty sure the unittest fails because circle-ci wasn't able to run 32-bit binary. I have the same behavior on my box; after I have add support for 32-bits elf (sudo dpkg --add-architecture i386; sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386) unit tests complete succesfully. 

So I dunno  what is the best way to handle this: do you usually put a swicth on your unit test file to run specific test based on the box architecture and os you are running on? Let me know what you want me to do :D

```
# python3 -m unittest vdb/tests/testrecon.py

<OUTPUT TRUNCATED>
._parseSectionRelocs: Reloc section differs from Dynamics: 0xb14
_parseSectionRelocs: Reloc section differs from Dynamics: 0xb4c
Failed to resolve breakpoint address for expression: libc.exit (delayed resolution?)
/home/cmaruti/vivisect/vivtestfiles-master/linux/i386/chgrp.llvm: missing operand
Try '/home/cmaruti/vivisect/vivtestfiles-master/linux/i386/chgrp.llvm --help' for more information.
RECON: 3452 0xf7dead80 libc.exit (libc._IO_2_1_stderr_, 0x00000001, 0xf7f94884, chgrp., chgrp.calloc())
.
----------------------------------------------------------------------
Ran 2 tests in 22.185s

OK
```

2023-01-21 13:14 UTC, atlas0fd00m approved these changes
awesome.  well done, @cmaruti and thank you!

2023-01-21 13:15 UTC, merged